// <auto-generated />
namespace DALWHOLEPOS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class DALComplete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DALComplete));
        
        string IMigrationMetadata.Id
        {
            get { return "202411211346196_DALComplete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
