// <auto-generated />
namespace DALWHOLEPOS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initDB0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initDB0));
        
        string IMigrationMetadata.Id
        {
            get { return "202410291449456_initDB0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
